# Generated by Django 5.2.13 on 2026-04-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('entity_count', models.IntegerField(default=0)),
                ('relationship_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph_answer', models.TextField(blank=True, null=True)),
                ('vector_answer', models.TextField(blank=True, null=True)),
                ('hybrid_answer', models.TextField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_method', models.CharField(max_length=50)),
                ('graph_score', models.FloatField(default=0)),
                ('vector_score', models.FloatField(default=0)),
                ('hybrid_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphrag.query')),
            ],
        ),
    ]
